import { promises as fs } from 'fs';
import { timingSafeEqual } from 'crypto';
import path from 'path';
import { NextResponse } from 'next/server';
import { getProviderStatus } from '../../../lib/agentProvider';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

type EngineLayerInput = {
  provider?: string;
  model?: string;
  baseUrl?: string;
  apiKey?: string;
};

type SharedConnectionInput = {
  baseUrl?: string;
  apiKey?: string;
};

type ModelConfigInput = {
  connection?: SharedConnectionInput;
  text?: EngineLayerInput;
  image?: EngineLayerInput;
  video?: EngineLayerInput;
};

const envPath = path.join(process.cwd(), '.env.local');

function isLocalRequest(req?: Request) {
  if (process.env.NODE_ENV !== 'production') return true;

  const host = req?.headers.get('host') || '';
  return host.startsWith('localhost:') || host.startsWith('127.0.0.1:') || host.startsWith('[::1]:');
}

function getRequestToken(req?: Request) {
  const direct = req?.headers.get('x-model-config-token')?.trim();
  if (direct) return direct;
  const auth = req?.headers.get('authorization') || '';
  if (auth.toLowerCase().startsWith('bearer ')) return auth.slice(7).trim();
  return '';
}

function matchesAdminToken(req?: Request) {
  const expected = process.env.MODEL_CONFIG_ADMIN_TOKEN?.trim();
  const provided = getRequestToken(req);
  if (!expected || !provided) return false;
  const expectedBuffer = Buffer.from(expected);
  const providedBuffer = Buffer.from(provided);
  return expectedBuffer.length === providedBuffer.length && timingSafeEqual(expectedBuffer, providedBuffer);
}

function getConfigAccess(req?: Request) {
  if (process.env.ALLOW_BROWSER_MODEL_CONFIG === 'true') {
    return { writable: true, authRequired: false, mode: 'explicit' };
  }
  if (process.env.ALLOW_BROWSER_MODEL_CONFIG === 'false') {
    return { writable: false, authRequired: false, mode: 'disabled' };
  }
  if (isLocalRequest(req)) {
    return { writable: true, authRequired: false, mode: 'local' };
  }
  if (process.env.MODEL_CONFIG_ADMIN_TOKEN?.trim()) {
    return { writable: matchesAdminToken(req), authRequired: true, mode: 'admin-token' };
  }
  return { writable: false, authRequired: false, mode: 'production' };
}

function parseEnv(text: string) {
  const env = new Map<string, string>();
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const index = trimmed.indexOf('=');
    if (index <= 0) continue;
    const key = trimmed.slice(0, index).trim();
    let value = trimmed.slice(index + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env.set(key, value);
  }
  return env;
}

function serializeValue(value: string) {
  if (/^[A-Za-z0-9_./:@+-]*$/.test(value)) return value;
  return JSON.stringify(value);
}

function serializeEnv(env: Map<string, string>) {
  const order = [
    'DEFAULT_PROVIDER',
    'DEMO_MODE',
    'ANTHROPIC_API_KEY',
    'ANTHROPIC_MODEL',
    'OPENAI_API_KEY',
    'OPENAI_MODEL',
    'OPENAI_BASE_URL',
    'CUSTOM_API_KEY',
    'CUSTOM_BASE_URL',
    'CUSTOM_MODEL',
    'IMAGE_PROVIDER',
    'IMAGE_API_KEY',
    'IMAGE_BASE_URL',
    'IMAGE_MODEL',
    'VIDEO_PROVIDER',
    'VIDEO_API_KEY',
    'VIDEO_BASE_URL',
    'VIDEO_MODEL'
  ];
  const lines = ['# Generated by VideoAgent model settings. Do not commit real keys.', ''];
  for (const key of order) {
    if (env.has(key)) lines.push(`${key}=${serializeValue(env.get(key) || '')}`);
  }
  for (const [key, value] of env) {
    if (!order.includes(key)) lines.push(`${key}=${serializeValue(value)}`);
  }
  return `${lines.join('\n')}\n`;
}

function setIfValue(env: Map<string, string>, key: string, value?: string) {
  if (value === undefined) return;
  env.set(key, value.trim());
  process.env[key] = value.trim();
}

function setSecretIfProvided(env: Map<string, string>, key: string, value?: string) {
  if (!value?.trim()) return;
  setIfValue(env, key, value);
}

function safeLayer(layer: EngineLayerInput | undefined): EngineLayerInput {
  return {
    provider: layer?.provider?.trim() || '',
    model: layer?.model?.trim() || '',
    baseUrl: layer?.baseUrl?.trim() || '',
    apiKey: layer?.apiKey?.trim() || ''
  };
}

function safeConnection(connection: SharedConnectionInput | undefined): SharedConnectionInput {
  return {
    baseUrl: connection?.baseUrl?.trim() || '',
    apiKey: connection?.apiKey?.trim() || ''
  };
}

export async function GET(req: Request) {
  const access = getConfigAccess(req);
  return NextResponse.json({
    ok: true,
    ...access,
    provider: getProviderStatus()
  });
}

export async function POST(req: Request) {
  const access = getConfigAccess(req);
  if (!access.writable) {
    return NextResponse.json(
      {
        ok: false,
        ...access,
        error: access.authRequired
          ? '模型配置写入需要管理口令。请填写 MODEL_CONFIG_ADMIN_TOKEN 对应的口令后再保存。'
          : '模型配置写入已被服务器拒绝。线上环境请设置 MODEL_CONFIG_ADMIN_TOKEN，或仅在可信内网显式设置 ALLOW_BROWSER_MODEL_CONFIG=true。'
      },
      { status: 403 }
    );
  }

  const body = (await req.json()) as ModelConfigInput;
  const text = safeLayer(body.text);
  const image = safeLayer(body.image);
  const video = safeLayer(body.video);
  const connection = safeConnection(body.connection);

  let current = '';
  try {
    current = await fs.readFile(envPath, 'utf8');
  } catch (_) {}
  const env = parseEnv(current);

  setIfValue(env, 'DEMO_MODE', '0');

  if (body.connection) {
    const sharedBaseUrl = connection.baseUrl || '';
    const sharedKey = connection.apiKey || '';
    const textModel = text.model || 'gpt-4.1-mini';
    const imageModel = image.model || 'gpt-image-1';
    const videoModel = video.model || 'agnes-video-v2.0';
    const sharedProvider = sharedBaseUrl ? 'custom' : 'openai';

    setIfValue(env, 'DEFAULT_PROVIDER', sharedProvider);
    if (sharedProvider === 'custom') {
      setSecretIfProvided(env, 'CUSTOM_API_KEY', sharedKey);
      setIfValue(env, 'CUSTOM_BASE_URL', sharedBaseUrl);
      setIfValue(env, 'CUSTOM_MODEL', textModel);
    } else {
      setSecretIfProvided(env, 'OPENAI_API_KEY', sharedKey);
      setIfValue(env, 'OPENAI_BASE_URL', '');
      setIfValue(env, 'OPENAI_MODEL', textModel);
    }

    setIfValue(env, 'IMAGE_PROVIDER', sharedBaseUrl ? 'custom' : 'openai');
    setIfValue(env, 'IMAGE_MODEL', imageModel);
    setIfValue(env, 'IMAGE_BASE_URL', sharedBaseUrl);
    setSecretIfProvided(env, 'IMAGE_API_KEY', sharedKey);

    setIfValue(env, 'VIDEO_PROVIDER', sharedBaseUrl ? 'custom' : 'agnes');
    setIfValue(env, 'VIDEO_MODEL', videoModel);
    setIfValue(env, 'VIDEO_BASE_URL', sharedBaseUrl);
    setSecretIfProvided(env, 'VIDEO_API_KEY', sharedKey);
  } else {
    if (text.provider) {
      setIfValue(env, 'DEFAULT_PROVIDER', text.provider);
      if (text.provider === 'anthropic') {
        setSecretIfProvided(env, 'ANTHROPIC_API_KEY', text.apiKey);
        setIfValue(env, 'ANTHROPIC_MODEL', text.model || 'claude-sonnet-4-5');
      } else if (text.provider === 'openai') {
        setSecretIfProvided(env, 'OPENAI_API_KEY', text.apiKey);
        setIfValue(env, 'OPENAI_MODEL', text.model || 'gpt-4.1-mini');
        setIfValue(env, 'OPENAI_BASE_URL', text.baseUrl || '');
      } else if (text.provider === 'custom') {
        setSecretIfProvided(env, 'CUSTOM_API_KEY', text.apiKey);
        setIfValue(env, 'CUSTOM_MODEL', text.model || '');
        setIfValue(env, 'CUSTOM_BASE_URL', text.baseUrl || '');
      }
    }

    setIfValue(env, 'IMAGE_PROVIDER', image.provider || '');
    setIfValue(env, 'IMAGE_MODEL', image.model || '');
    setIfValue(env, 'IMAGE_BASE_URL', image.baseUrl || '');
    setSecretIfProvided(env, 'IMAGE_API_KEY', image.apiKey);

    setIfValue(env, 'VIDEO_PROVIDER', video.provider || '');
    setIfValue(env, 'VIDEO_MODEL', video.model || '');
    setIfValue(env, 'VIDEO_BASE_URL', video.baseUrl || '');
    setSecretIfProvided(env, 'VIDEO_API_KEY', video.apiKey);
  }

  await fs.writeFile(envPath, serializeEnv(env), { mode: 0o600 });

  return NextResponse.json({
    ok: true,
    ...access,
    provider: getProviderStatus()
  });
}
